### ISSUE TITLE
Issue starting the server-pro containers for hbbs/hbbr

### ISSUE THREAD

**Issue by fgn-itsupport** [rustdesk/rustdesk-server#422]
I'm trying to start the hbbs and the hbbr via container. Both containers are failing with the following error: 

hbbs    | thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flexi_logger-0.25.6/src/threads.rs:107:14:
hbbs    | called Result::unwrap() on an Err value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }

The same error occurs for hbbr as well. 

**Describe the environment**
 - Install environment: docker
 - If available, the `docker-compose.yaml` file:
 
 services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server-pro:latest
    #environment:
      #RUST_BACKTRACE: full
      #RUST_BACKTRACE: 1
    command: hbbs
    volumes:
      - ./data:/root
    network_mode: "host"

    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server-pro:latest
    #environment:
      #RUST_BACKTRACE: full
      #RUST_BACKTRACE: 1
    command: hbbr
    volumes:
      - ./data:/root
    network_mode: "host"
    restart: unless-stopped

 
 - In any case, you have to specify the version in use
rustdesk-server-pro : latest 
ImageID: ccc00beaef31

**How to Reproduce the bug**
1. Given the previously described environment
2. docker-compose up 
3. I get the following error: 
hbbs    | thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flexi_logger-0.25.6/src/threads.rs:107:14:
hbbs    | called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
hbbs    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
hbbr    | thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/flexi_logger-0.25.6/src/threads.rs:107:14:
hbbr    | called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
hbbr    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Expected behavior**
both container should start

**Additional context**
The same oss version container do work without any issue.

**Comment by rustdesk** [comment]
Try out this,

https://github.com/denoland/deno/issues/17444#issuecomment-2038465524
