### ISSUE TITLE
Build fails on CentOS Stream 9 (ppc64le)

### ISSUE THREAD

**Issue by bkeys** [rustdesk/rustdesk-server#89]
**Describe the bug**
I try to build the rustdesk-server and it fails. I am including a backtrace of the failed build.

**Describe the environment**
 - Install environment: I am building this from source on ppc64le CentOS Stream 9
Version: 1.1.6

**How to Reproduce the bug**
Download rustdesk-server 1.1.6
run 
3. The build goes just fine until I get this error

```
   Compiling sha-1 v0.10.0
   Compiling sha2 v0.10.2
   Compiling blowfish v0.9.1
   Compiling quickcheck v1.0.3
   Compiling headers v0.3.7
error: failed to run custom build command for `ring v0.16.20`

Caused by:
  process didn't exit successfully: `/home/bkeys/rustdesk-server-1.1.6/target/release/build/ring-85728e837d72d846/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/bkeys/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/build.rs:358:10
  stack backtrace:
     0:        0x12a86d4f0 - std::backtrace_rs::backtrace::libunwind::trace::hf56bdb6f3c25f4c4
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:        0x12a86d4f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h0ce20f74b7f99b53
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:        0x12a86d4f0 - std::sys_common::backtrace::_print_fmt::hf545a16641103423
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:66:5
     3:        0x12a86d4f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::ha7ca998471a9c19c
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:45:22
     4:        0x12a8a7408 - core::fmt::write::h220453ed281bfc46
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/fmt/mod.rs:1196:17
     5:        0x12a867778 - std::io::Write::write_fmt::h8c2cc8ee5fce6f96
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/io/mod.rs:1654:15
     6:        0x12a86fab8 - std::sys_common::backtrace::_print::h0aa7a837abf814ee
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:48:5
     7:        0x12a86fab8 - std::sys_common::backtrace::print::h1f7eca093c91527e
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:35:9
     8:        0x12a86fab8 - std::panicking::default_hook::{{closure}}::h8d933b7ca4a8af24
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:295:22
     9:        0x12a86f524 - std::panicking::default_hook::hf8bc6d93bc4dee42
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:314:9
    10:        0x12a8703a0 - std::panicking::rust_panic_with_hook::h9908d6370d2fd1d1
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:698:17
    11:        0x12a87001c - std::panicking::begin_panic_handler::{{closure}}::h903584fd4a442833
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:586:13
    12:        0x12a86db28 - std::sys_common::backtrace::__rust_end_short_backtrace::h8d48245d0cce9e2e
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/sys_common/backtrace.rs:138:18
    13:        0x12a86fc5c - rust_begin_unwind
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
    14:        0x12a7aea54 - core::panicking::panic_fmt::h8a58f04e1760c429
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
    15:        0x12a7ae8d0 - core::panicking::panic::h3027ef1a03dece45
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:48:5
    16:        0x12a7baf7c - core::option::Option<T>::unwrap::h5926cf32285a7702
    17:        0x12a7b3abc - build_script_build::build_c_code::hc8670a23099248c0
    18:        0x12a7b3180 - build_script_build::ring_build_rs_main::h337e7b7fc5c0dcc5
    19:        0x12a7b2a44 - build_script_build::main::h49d060151e4f9df0
    20:        0x12a7b8ed8 - core::ops::function::FnOnce::call_once::he9aeadfeeae1561d
    21:        0x12a7b8a28 - std::sys_common::backtrace::__rust_begin_short_backtrace::hb20332084fc4c5f8
    22:        0x12a7c706c - std::rt::lang_start::{{closure}}::h838d360d9295f7f6
    23:        0x12a860c14 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb2f4fd5168d6ae14
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:280:13
    24:        0x12a860c14 - std::panicking::try::do_call::h18538895b6705793
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
    25:        0x12a860c14 - std::panicking::try::h3a2f1cdfb5ea18e0
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
    26:        0x12a860c14 - std::panic::catch_unwind::h22e588cd92673cee
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
    27:        0x12a860c14 - std::rt::lang_start_internal::{{closure}}::h0fce214361567d67
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:48
    28:        0x12a860c14 - std::panicking::try::do_call::h40e20ca9821799b3
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:492:40
    29:        0x12a860c14 - std::panicking::try::h83ed61147f56f9e6
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:456:19
    30:        0x12a860c14 - std::panic::catch_unwind::h4c914378c160183c
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panic.rs:137:14
    31:        0x12a860c14 - std::rt::lang_start_internal::he3c3468579f25135
                                 at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/rt.rs:128:20
    32:        0x12a7c7020 - std::rt::lang_start::h3626b86ffc0fa688
    33:        0x12a7b89e8 - main
    34:     0x7fff92213c24 - __libc_start_call_main
    35:     0x7fff92213e08 - __libc_start_main@GLIBC_2.17
    36:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
```

I don't think this is an issue with the machine being ppc64le, maybe we need a specific version of Rust?

**Comment by dlhxzb** [comment]
It's an old issue for [`ring`](https://github.com/briansmith/ring/issues/389) 👈

**Comment by paspo** [comment]
2016 issue...
Looks like they're working on it: https://github.com/briansmith/ring/pull/1057

Obviously we can't have ppc64le support until all deps are covered.

**Comment by clnperez** [comment]
this popped up in a google search today. 

https://github.com/briansmith/ring/pull/1057 was merged so if you want to try again you can. though i don't know if it's been put into a ring release yet
